### ISSUE TITLE
Add libraries accessor

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Wrapper#10]
Calling `pandoc --version` also gives information about libraries, e.g. 

    pandoc 1.18
    Compiled with pandoc-types 1.17.0.4, texmath 0.8.6.6, highlighting-kate 0.6.3

    pandoc 1.16.0.2
    Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.

This should be parsed and stored for access, e.g.

    pandoc->uses->{pandoc_types}; # version object or null
    pandoc->uses("pandoc_types"); # dito

**Comment by bpj** [comment]
Something like this?

``` perl
our $LIBRARY_NAME_RE = qr/\pL\w*(?:-\pL\w*)*/;
our $LIBRARY_VERSION_RE = qr/\s+($LIBRARY_NAME_RE)\s+(\d+(?:-\d+)*)/;

sub new {
    ...
    if ( $out =~ /Compiled with($LIBRARY_VERSION_RE+)/ ) {
        my %libs = $1 =~ /$LIBRARY_VERSION_RE/g;
        for my $name ( keys %libs ) {
            $libs{$name} = Pandoc::Version->new( $libs{$name} );
        }
        $pandoc->{libraries} = \%libs;
    }
    ...
}

sub lib_version {
    my( $pandoc, $name) = @_;
    unless ( ($name //= "") =~ /$LIBRARY_NAME_RE/ ) {
        croak "Doesn't look like a library name: $name";
    }
    unless ( ref $pandoc ) {
        $pandoc = $PANDOC //= Pandoc->new;
    }
    return $pandoc->{libraries}{$name} // Pandoc::Version->new();
}
```

Untested of course!

**Comment by nichtich** [comment]
Thanks, I'll integrate it and do a commit in your name!

**Comment by nichtich** [comment]
See https://github.com/nichtich/Pandoc-Wrapper/commit/84772774aba9e76e2d1960e5d862d78d3b98ebe3
Ready for release of 0.3.2?
