### ISSUE TITLE
Option overrides in methods should come after user-supplied arguments

### ISSUE THREAD

**Issue by bpj** [nichtich/Pandoc-Wrapper#16]
When a function runs pandoc and adds options to the arguments supplied by the user those added options should be listed *after* the user-supplied arguments so that the added options override any like options supplied by the user, and for good measure the `--output` option should also be overridden as `'-o' => '-'` since the methods concerned (`convert` and `file` unless I missed something) depend on pandoc's output actually going to STDOUT.

Thus where [convert](https://github.com/nichtich/Pandoc-Wrapper/blob/master/lib/Pandoc.pm#L153) says

``` perl
my $status = $pandoc->run( [ '-f' => $from, '-t' => $to, @_ ], \%opts );
```

it should better say

``` perl
my $status = $pandoc->run( [ @_, '-f' => $from, '-t' => $to, '-o' => '-' ], \%opts );
```

and where [file](https://github.com/nichtich/Pandoc-Wrapper/blob/master/lib/Pandoc.pm#L184) says

``` perl
my @args = ('-t' => 'json', @_);
```

it should better say

``` perl
my @args = (@_, '-t' => 'json', '-o' => '-');
```

**Comment by nichtich** [comment]
You are right. Can you create a pull request?

On 24. Januar 2017 12:50:47 MEZ, Benct Philip Jonsson <notifications@github.com> wrote:
>When a function runs pandoc and adds options to the arguments supplied
>by the user those added options should be listed *after* the
>user-supplied arguments so that the added options override any like
>options supplied by the user, and for good measure the `--output`
>option should also be overridden as `'-o' => '-'` since the methods
>concerned (`convert` and `file` unless I missed something) depend on
>pandoc's output actually going to STDOUT.
>
>Thus where
>[convert](https://github.com/nichtich/Pandoc-Wrapper/blob/master/lib/Pandoc.pm#L153)
>says
>
>``` perl
>my $status = $pandoc->run( [ '-f' => $from, '-t' => $to, @_ ], \%opts
>);
>```
>
>it should better say
>
>``` perl
>my $status = $pandoc->run( [ @_, '-f' => $from, '-t' => $to, '-o' =>
>'-' ], \%opts );
>```
>
>and where
>[file](https://github.com/nichtich/Pandoc-Wrapper/blob/master/lib/Pandoc.pm#L184)
>says
>
>``` perl
>my @args = ('-t' => 'json', @_);
>```
>
>it should better say
>
>``` perl
>my @args = (@_, '-t' => 'json', '-o' => '-');
>```
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nichtich/Pandoc-Wrapper/issues/16

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by bpj** [comment]
Den 2017-01-24 kl. 17:08, skrev Jakob Voß:
> You are right. Cannabis you create a pull request?

Sure, but I should probably do it sober! ;-)

I'll make the PR tomorrow.

(Sorry for late reply. I still have an issue with my GitHub 
notification emails.)
