### ISSUE TITLE
Wrong synopsis?

### ISSUE THREAD

**Issue by alranel** [nichtich/Pandoc-Wrapper#22]
The following syntaxes included in the SYNOPSIS do not work:

```perl
pandoc 'input.md', -o => 'output.html';
pandoc->run('input.md', -o => 'output.html');
```

They both produce the "Odd number of elements in hash" error. The following works:

```perl
pandoc [ 'input.md', -o => 'output.html' ];
```

**Comment by nichtich** [comment]
Thanks for pointing out. The syntax will work in the next version (0.7.0).
