### ISSUE TITLE
Capture PDF output to scalar

### ISSUE THREAD

**Issue by alranel** [nichtich/Pandoc-Wrapper#23]
It would handy to do the following:

```perl
pandoc -f => 'html', -t => 'pdf', { in => \$html, out => \$pdf };
```

However pandoc does not support `-t pdf` as it only allows to output PDF to a file instead of STDOUT. It would be handy if this module would provide this functionality. It can be done by writing to a temporary file with `File::Temp`.

(Thank you for this handy module!)

**Comment by nichtich** [comment]
Sorry but `pdf` is no pandoc output format (as listed with `output_formats`) so supporting this would introduce inconsistencies. Better directly use `File::Temp` and provide the filename with `-o $filename`.
