### ISSUE TITLE
Failure with pandoc 2?

### ISSUE THREAD

**Issue by teoric** [nichtich/Pandoc-Wrapper#25]
Should it be documented that this module only supports pandoc 1?  My pandoc is 2.1.3, and it reports while testing:

> t/convert.t ............. 1/? --smart/-S has been removed.  Use +smart or -smart extension instead.
> For example: pandoc -f markdown+smart -t markdown-smart.
> Try pandoc --help for more information.
>  at t/convert.t line 11.

(The removal of `--smart/-s` several comes up three times.)

Pandoc 2.1.3, Perl 5.26.1

**Comment by bpj** [comment]
It's not the module's fault. You have to remove the `--smart` option from
the command options and replace it with the `+smart` extension on the input
format:

    pandoc->convert('markdown+smart' => 'html', ...)

but note that you may not need to turn on smartness explicitly as Pandoc 2
has it on by default for Markdown input.

Also note that `markdown+smart` as *output* format has the opposite effect:
it removes smartness!


Den mån 2 apr 2018 09:28teoric <notifications@github.com> skrev:

**Comment by teoric** [comment]
I see.  At the moment, the module uses `--smart` in a **test**, which breaks install if Pandoc is new enough. This is not under the control of users and should be fixed if the intention is to support Pandoc 2.  (Sorry, I just installed this as a dependency and noticed the install failure.)

E.g. in `t/convert.t`, line 11:
```perl
my $html = pandoc->convert('markdown' => 'html', '...', '--smart');
```

**Comment by bpj** [comment]
Den 2018-04-02 kl. 11:21, skrev teoric:
> I see.  At the moment, the module uses `--smart` in a **test**, which breaks install if Pandoc is new enough. This is not under the control of users and should be fixed if the intention is to support Pandoc 2.  (Sorry, I just installed this as a dependency and noticed the install failure.)
> 
> E.g. in `t/convert.t`, line 11:
> ```perl
> my $html = pandoc->convert('markdown' => 'html', '...', '--smart');
> ```
> 
> 

I see. So we need to check the pandoc version in those tests and 
differentiate the test based on that.  @nichtich, I can  send a PR 
for this if you like since I'm free the next few days.

**Comment by nichtich** [comment]
Thanks for notification! I fixed the tests and [created methods](https://metacpan.org/pod/release/VOJ/Pandoc-0.7.1/lib/App/Prove/Plugin/andoc.pm) to check against *all* available pandoc versions.
