### ISSUE TITLE
$ENV{HOME} on Windows

### ISSUE THREAD

**Issue by TakeAsh** [nichtich/Pandoc-Wrapper#30]
There is a warning (not error) message on Windows.
`Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at \Pandoc-Wrapper\lib/Pandoc.pm line 50.`

The environment variable "HOME" is not defined by default on Windows.
But we can use "USERPROFILE" instead of "HOME".
It might be better to change Pandoc.pm line 50 like below.
`my $bindir = ( $ENV{HOME} || $ENV{USERPROFILE} ) . "/.pandoc/bin";`

**Comment by nichtich** [comment]
Thanks, I've fixed this in 0.8.1 and added basic [automatic testing with Windows](https://ci.appveyor.com/project/nichtich/pandoc-wrapper). The test, however does not run with Pandoc executable unless I've found out how to install Pandoc automatically on Windows.

**Comment by TakeAsh** [comment]
I'm sorry.
$ENV{USERPROFILE} is not suitable.
In Unix, the default data directory is `$ENV{HOME}/.pandoc`.
But in Windows the default data directory is `C:\Users\USERNAME\AppData\Roaming\pandoc`.
https://pandoc.org/MANUAL.html#general-options
This might be `$ENV{APPDATA}/pandoc`.
There is no dot at the top of `pandoc` in Windows, so platform detection is needed.

**Comment by nichtich** [comment]
Thanks, I'll fix this!
