### ISSUE TITLE
Windows test with Pandoc executable

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Wrapper#31]
Tests are run at https://ci.appveyor.com/ but `.appveyor.yml` should be extended to install Pandoc and run test again with executable, otherwise most tests are skipped anyway.

**Comment by TakeAsh** [comment]
As same as strawberryperl, Pandoc can be installed by Chocolatey.
```
cinst -y strawberryperl pandoc wkhtmltopdf
```
https://chocolatey.org/packages/pandoc
https://chocolatey.org/packages/wkhtmltopdf

PlantUML can be installed by Chocolatey, too.
```
cinst -y plantuml
```
https://chocolatey.org/packages/plantuml

**Comment by nichtich** [comment]
Thanks! I'll add this to other Pandoc modules as well :-)
