### ISSUE TITLE
failed to fetch https://api.github.com/repos/jgm/pandoc/releases/tags/

### ISSUE THREAD

**Issue by vanHoesel** [nichtich/Pandoc-Wrapper#33]
when I try to run `perl -MPandoc::Release -e 'my $pandoc = get(2.1.3)->download'` I get an error "failed to fetch https://api.github.com/repos/jgm/pandoc/releases/tags/

But GitHub is probably trying to tell you that you make the wrong API call, trying to access the same endpoint wit `curl` it answers with:
```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name"
}
```

See [Get a release by Tag Name](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name)

Once fixed, I can install a more recent version than the debian-package provides: `v1.17.2`

**Comment by nichtich** [comment]
Try `perl -MPandoc::Release -e 'my $pandoc = get("2.1.3")->download`

**Comment by vanHoesel** [comment]
yep, that works
