### ISSUE TITLE
add symlink to installed version of pandoc

### ISSUE THREAD

**Issue by vanHoesel** [nichtich/Pandoc-Wrapper#35]
When using Pandoc::Release, it installs a binary at some location, but as `pandoc-2.2.1`. But that location and the filename are not very convenient.

There is an option that will set the location of where to install with `bin => /opt/local/pandoc`, but i'd really love to have to option to pass in a link to: `link => /usr/bin/pandoc`. That would create a symlink to the just installed release version. If `link` is a directory, then it should be a link called `pandoc`, otherwise it should create the link with the exact specified name.

**Comment by nichtich** [comment]
I implemented such feature with https://github.com/nichtich/Pandoc-Wrapper/commit/41acd71218b2f9c45be8b6c6b83565fa04d7898e but not tested nor documented. I guess some edge cases (relative pathes, existing symlink...) need to be covered first. More input is welcome!

**Comment by vanHoesel** [comment]
looking forward, so, i can strip a lot of code from out Docker File and the local `install_pandoc`. Made a few comments on your proposed changes

**Comment by nichtich** [comment]
Just release 0.8.5. This should work then:

    cpanm Pandoc 
    perl -MPandoc::Release -E 'latest->download->symlink'
    PATH=~/.pandoc/bin:$PATH
    pandoc --version
